### Localhost
# @baseUrl = http://localhost:5052/api
### Docker 
# @baseUrl = http://localhost:8080/api
### Node Port
# @baseUrl = http://localhost:31374/api
### Ingress
@baseUrl = https://iamsivas.com/api

#### Platform Service
### Get App Platforms
GET {{baseUrl}}/platforms

### Create Platform
POST {{baseUrl}}/platforms
Content-Type: application/json

{
  "name": "C++",
  "publisher": "CPP",
  "cost": "Free"
}

### GetPlatformById
GET {{baseUrl}}/platforms/1


## Get All Platforms
## Get All Commands for a Platform
## Get a command for a Platform
## Create a Command for a Platform
